stages:
  - deploy
  - renew

deploy:
  stage: deploy
  rules:
    - if: '$RUN_DEPLOY == "true"'
  tags:
    - docker
  image: 
    name: bitnami/kubectl:1.21
    entrypoint: [""]
  environment:
    name: development
    url: https://ray2021.k8s.pdis.dev
  script:
    - DOMAIN=$(echo "$CI_ENVIRONMENT_URL" | awk -F/ '{print $3}')
    - sed -i "s,<DOMAIN>,$DOMAIN,g" .kubernetes.yml
    - sed -i "s,<REPO_URL>,$REPO_URL,g" .kubernetes.yml
    - kubectl create secret docker-registry gitlab
      --docker-server=$CI_REGISTRY --docker-username=$REGISTRY_USER --docker-password=$REGISTRY_PASSWORD
      --dry-run -o yaml | kubectl apply -f -
    - kubectl apply -f .kubernetes.yml

renew:
  stage: renew
  tags:
    - docker
  image: 
    name: bitnami/kubectl:1.21
    entrypoint: [""]
  environment:
    name: development
    url: https://ray2021.k8s.pdis.dev
  script:
    - kubectl rollout restart deployment/ray2021 -n $KUBE_NAMESPACE