apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray2021
  labels:
    app: ray2021
spec:
  selector:
    matchLabels:
      app: ray2021
  replicas: 2
  template:
    metadata:
      labels:
        app: ray2021
    spec:
      containers:
        - name: nginx
          image: gitlab.pdis.dev:5050/web-application/hexo-web-server-image:main
          env:
            - name: REPO_URL
              value: <REPO_URL>
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab

---
apiVersion: v1
kind: Service
metadata:
  name: ray2021
  labels:
    app: ray2021
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: ray2021

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ray2021
  labels:
    app: ray2021
spec:
  rules:
    - host: <DOMAIN>
      http:
        paths:
          - backend:
              serviceName: ray2021
              servicePort: 80
